//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFRichTextBox.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFRichTextBox.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;New Bug Template&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;header 1&lt;/h1&gt;
        ///		&lt;p&gt;
        ///			&lt;span style=&quot;color:Red; font-weight:bold;&quot;&gt;RED TEXT&lt;/span&gt;
        ///			&lt;br /&gt;
        ///			1. Text after break
        ///		&lt;/p&gt;
        ///		&lt;h2&gt;header 2&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			&lt;span style=&quot;color:Green; font-weight:bold;&quot;&gt;GREEN TEXT&lt;/span&gt;
        ///			&lt;br /&gt;
        ///			&lt;a href=&quot;http://www.test.de&quot;&gt;a hyperlink&lt;/a&gt;
        ///		&lt;/p&gt;
        ///		&lt;div&gt;
        ///			&lt;span style=&quot;color:Red; font-weight:bold;&quot;&gt;TEXT IN DIV&lt;/span&gt;
        ///		&lt;/d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HTMLPage1 {
            get {
                return ResourceManager.GetString("HTMLPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;font-family:BlinkMacSystemFont, &amp;quot;background-color:#FFFFFF;&quot;&gt;本系列视频课程为适配课后服务双重场景的“悦”读类课后服务，适合小学学段。&lt;/span&gt;&lt;br /&gt;&lt;span style=&quot;font-family:BlinkMacSystemFont, &amp;quot;background-color:#FFFFFF;&quot;&gt;课程包含大猫英语分级阅读预备级至八级、共144本读物的阅读精讲视频课，总时长近144学时（按照40分钟/学时）。视频课程采用教师讲授、师生互动的形式，通过趣味热身导入，资深名师全方位解读绘本，课堂贯穿多种阅读策略，全面提升学生的阅读能力，并注重学以致用，情感升华，培养跨文化意识，树立正向价值观。&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span style=&quot;font-family:BlinkMacSystemFont, &amp;quot;background-color:#FFFFFF;&quot;&gt;课程可配合“大猫英语分级阅读”读物使用。“大猫英语分级阅读”旨在为4-18岁中国少年儿童英语阅读提供全面解决方案，图书为教育 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HTMLPage2 {
            get {
                return ResourceManager.GetString("HTMLPage2", resourceCulture);
            }
        }
    }
}
